#!/bin/bash

echo "------ HOOK START - BUILD -------"
# printenv
# https://docs.docker.com/docker-cloud/builds/advanced/
docker build \
       --build-arg auth=$AUTH \
       --build-arg branch=$BRANCH \
       --build-arg django_secret_key=$DJANGO_SECRET_KEY \
       --build-arg POSTGRES_DB=$POSTGRES_DB \
       --build-arg POSTGRES_USER=$POSTGRES_USER \
       --build-arg POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
       --build-arg DJANGO_ADMIN_NAME=$DJANGO_ADMIN_NAME \
       --build-arg DJANGO_ADMIN_EMAIL=$DJANGO_ADMIN_EMAIL \
       --build-arg DJANGO_ADMIN_PASSWORD=$DJANGO_ADMIN_PASSWORD \
       -t $IMAGE_NAME -f ./Dockerfile ../..

echo "------ HOOK END - BUILD -------"
